import { TemplateFamily, TemplateDefinition } from './types';

export const TEMPLATES: Record<TemplateFamily, TemplateDefinition> = {
  'retail-core': {
    family: 'retail-core',
    label: 'Retail Core',
    kicker: 'Editorial commerce',
    headline: 'Launch a storefront that looks premium from day one.',
    summary: 'Built for shops and product businesses that need strong catalog presentation and fast conversion paths.',
    demoUrl: 'https://cedarandforge.edgemarketplacehub.com',
    primaryColor: '#1A1A1A',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: '0px',
  },
  'service-pro': {
    family: 'service-pro',
    label: 'Service Pro',
    kicker: 'Trust-first services',
    headline: 'Turn expertise into a high-converting service site.',
    summary: 'Optimized for quotes, bookings, before/after proof, and clear service packaging.',
    demoUrl: 'https://bloomandlore.edgemarketplacehub.com',
    primaryColor: '#2563eb',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: '4px',
  },
  'food-catering': {
    family: 'food-catering',
    label: 'Food & Catering',
    kicker: 'Menus + booking',
    headline: 'Show the menu, prove the quality, and get booked quickly.',
    summary: 'Designed for restaurants, food trucks, catering brands, and event menus.',
    demoUrl: 'https://earthandember.edgemarketplacehub.com',
    primaryColor: '#ea580c',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: '12px',
  },
  'artisan-market': {
    family: 'artisan-market',
    label: 'Artisan Market',
    kicker: 'Maker storytelling',
    headline: 'Sell craft with a story customers can feel.',
    summary: 'For makers, local brands, and handmade businesses where provenance and product detail matter.',
    demoUrl: 'https://apexconsulting.edgemarketplacehub.com',
    primaryColor: '#b45309',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: '0px',
  },
  'event-floral': {
    family: 'event-floral',
    label: 'Event & Floral',
    kicker: 'Gallery-led luxury',
    headline: 'Lead with beauty, then turn inspiration into inquiries.',
    summary: 'Ideal for florists, planners, rentals, and event creatives selling premium visual services.',
    demoUrl: 'https://eventfloral.edgemarketplacehub.com',
    primaryColor: '#be185d',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: '24px',
  },
  'coach-educator': {
    family: 'coach-educator',
    label: 'Coach & Educator',
    kicker: 'Transformation-focused',
    headline: 'Sell expertise, not just content.',
    summary: 'Built for coaches, course creators, and educators who need to convert visitors into clients.',
    demoUrl: 'https://vantagecoaching.edgemarketplacehub.com',
    primaryColor: '#7c3aed',
    fontFamily: 'Inter, system-ui, sans-serif',
    borderRadius: '8px',
  },
};
